### ISSUE TITLE
Cannot input slash('/') in editor

### ISSUE THREAD

**Issue by wcho** [webida/webida-client#228]
Reproduction: Open text file. Try to input slashes. I cannot input slash('/') in editor.
Other input boxes in dialogs are ok.
Other than slash can be input.
There's no special error message in console.
I found that the following commit introduced the bug.

a41d012903a030e444a887910863610831024918 is the first bad commit
commit a41d012903a030e444a887910863610831024918

**Comment by happibum** [comment]
It turned out that before introducing bower webida-client included a copy of codemirror v4.9 from https://github.com/webida/CodeMirror/commit/36d6ae1b5b271b217124fedcdcec439649e7136d, commited on early January.

But the github.com/webida/codemirror#fork was updated to v4.12 around mid February,
which has the slash problem.
Reverting the codemirror repository will solve the problem.

**Comment by cimfalab** [comment]
Dear,
this is some annoying issue when editing source files :)
Please consider it in high priority.
Thank you.
