### ISSUE TITLE
'Beautify All' makes wrong comment.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#293]
1. cursor exists in comment
2. Execute 'Beautify All'

---> It makes unexpected comment.

Before beautify,
![beautifybefore](https://cloud.githubusercontent.com/assets/7767406/8898765/afeb350e-3465-11e5-9176-38779e6151e4.png)

After beautify,
![beautifyafter](https://cloud.githubusercontent.com/assets/7767406/8898768/b693a5b2-3465-11e5-8414-8a87aeabf36c.png)

**Comment by hyukmin-kwon** [comment]
This issue is same as #394.

**Comment by hyukmin-kwon** [comment]
* This bug is due to cursor positioning logic which inserts a special temporary comment at current cursor position and move the cursor position to that position after beautifying process.
 * We will change the positioning logic to preserve the number of  non-whitespace characters before cursor positions.
