### ISSUE TITLE
Shift + Alt + B (Beautify All) works strangely in current line.

### ISSUE THREAD

**Issue by lisyoen** [webida/webida-client#394]
01 /*
02 comment
03 */

if you press Shift+Alt+B when the cursor is located 3rd line, the line changes to '* /'.
(added space between * and /)

**Comment by hyukmin-kwon** [comment]
This issue is same as #293.

**Comment by hyukmin-kwon** [comment]
* This bug is due to cursor positioning logic which inserts a special temporary comment at current cursor position and move the cursor position to that position after beautifying process.
 * We will change the positioning logic to preserve the number of  non-whitespace characters before cursor positions.
