### ISSUE TITLE
Removing editors for deleted resources.

### ISSUE THREAD

**Issue by JUHYUNCHOI** [webida/webida-client#620]
refer to:https://github.com/webida/webida-client/issues/510

**Comment by hwshim** [comment]
#719 Solves this issue. Please check again.
Note that, I think 'dirty mark on deleted file' is not strange.
Because after delete the persistence, there is no contents to compare with model,
in this case, I think the model for that kind of editor could be considered as a new model.
(for the none existing file, just exists in the memory.)
