### ISSUE TITLE
[dashboard app] cannot find quota info

### ISSUE THREAD

**Issue by hgkang** [webida/webida-client#713]
I see "cannot find quota info" when I login with my account "hyungoo1.kang@samsung.com"

**Comment by kyungmi** [comment]
@hgkang Which server did you try to connect?

**Comment by kyungmi** [comment]
This was occurred on webida.org server at 2015-11-20.
It seems to be a problem related with the project files(projid, projects) that is managed by xfs_util with the "old" wfs.

**Comment by kyungmi** [comment]
The real problem turned out that there are no "xfs managed tree" on some project. I solved this with the `xfs_quota -xc "project -s {project}"; xfs_quota -xc "limit -p bhard=1G {project}"` commands (The `{project}` is same with the `wfsId`). But I could not find the reason why the managed tree had disappeared.
