### ISSUE TITLE
Use only one of dojo declare or genetic.inherit

### ISSUE THREAD

**Issue by wcho** [webida/webida-client#764]
Both of dojo declare and genetic.inherit are being used to implement classical inheritance. Both are working well but they are redundant. Only one of them needs to be used.
Personally, I prefer dojo declare because it doesn't require to define a function to define a class. It just returns the new class.

**Comment by hwshim** [comment]
You can check about the differences between above inheritances here.
http://confluence.score/pages/viewpage.action?pageId=30432235

I recommend use genetic.inherit except for inherit from existing dojo's classes.
Because
1) As mentioned above, dojo's inherited data structure is strange, it has __inherited method
that I never have defined.
2) dojo's inherited __proto__ is not the Constructor function but just Object, so we can be confusing exactly what is it.
3) finally dojo have following problem for strict mode.
http://dojo-toolkit.33424.n3.nabble.com/A-line-to-use-instead-of-quot-this-inherited-arguments-quot-in-strict-mode-td3999709.html
http://stackoverflow.com/questions/33208956/dojo-error-when-using-this-inheritedarguments-in-strict-mode

Anyway, genetic.inherit is just simplifies Object.create(), so I recommend that
for dojo's classes use dojo.declare and for others please use genetic.inherit() instead.

Thanks.

**Comment by hwshim** [comment]
In addition, I made myself such utilities before and used it for web editing framework like this.

![image](https://cloud.githubusercontent.com/assets/7447396/11437224/5bb6a6be-952f-11e5-91ee-0fd38d3f09f4.png)

But It had to intervene original javascript prototype inheritance in any way.
Actually the above code's instance returns such an object like the dojo's declare's instance.
I think It's heavy and confusing.
Object.create() is simple and easy so I simplifies it.

Thanks.

**Comment by hwshim** [comment]
If there's no problem I'll guide like the above.
"for dojo's classes use dojo.declare and for all others please use genetic.inherit()"
Thanks.
